"""empty message

Revision ID: 318c7fd5dff0
Revises: ef098dbbf8d7
Create Date: 2017-08-24 16:13:31.171812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '318c7fd5dff0'
down_revision = 'ef098dbbf8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('file_path', table_name='dataset')
    op.alter_column('tract', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tract', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_index('file_path', 'dataset', ['file_path'], unique=True)
    # ### end Alembic commands ###
