"""empty message

Revision ID: 3300935dbc12
Revises: 
Create Date: 2017-05-24 12:47:32.424925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3300935dbc12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('dataset', sa.String(length=12), nullable=True))
    op.add_column('subject', sa.Column('dataset_id', sa.String(length=12), nullable=True))
    op.add_column('subject', sa.Column('handedness', sa.String(length=1), nullable=True))
    op.add_column('subject', sa.Column('ravens_iq_raw', sa.Integer(), nullable=True))
    op.drop_index('atlas_id', table_name='subject')
    op.create_unique_constraint(None, 'subject', ['dataset_id'])
    op.drop_column('subject', 'brc_atlas')
    op.drop_column('subject', 'iq')
    op.drop_column('subject', 'atlas_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('atlas_id', mysql.VARCHAR(length=12), nullable=True))
    op.add_column('subject', sa.Column('iq', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('subject', sa.Column('brc_atlas', mysql.VARCHAR(length=1), nullable=True))
    op.drop_constraint(None, 'subject', type_='unique')
    op.create_index('atlas_id', 'subject', ['atlas_id'], unique=True)
    op.drop_column('subject', 'ravens_iq_raw')
    op.drop_column('subject', 'handedness')
    op.drop_column('subject', 'dataset_id')
    op.drop_column('subject', 'dataset')
    # ### end Alembic commands ###
