"""empty message

Revision ID: 3994ee8f2cc4
Revises: b9e14d4c45c0
Create Date: 2017-05-24 15:48:22.771675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3994ee8f2cc4'
down_revision = 'b9e14d4c45c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('code_temp', sa.String(length=12), nullable=False))
    op.add_column('dataset', sa.Column('file_path_temp', sa.String(length=20), nullable=False))
    op.drop_index('file_path', table_name='dataset')
    op.create_unique_constraint(None, 'dataset', ['file_path_temp'])
    op.drop_column('dataset', 'file_path')
    op.drop_column('dataset', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('code', mysql.VARCHAR(length=12), nullable=False))
    op.add_column('dataset', sa.Column('file_path', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'dataset', type_='unique')
    op.create_index('file_path', 'dataset', ['file_path'], unique=True)
    op.drop_column('dataset', 'file_path_temp')
    op.drop_column('dataset', 'code_temp')
    # ### end Alembic commands ###
