"""empty message

Revision ID: 3a1eaa6435d6
Revises: e0d868481cdd
Create Date: 2018-06-28 16:49:27.643862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a1eaa6435d6'
down_revision = 'e0d868481cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset_tracts', 'method_code',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset_tracts', 'method_code',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###
