"""empty message

Revision ID: 4a80166a46ec
Revises: 7f234c96d8f4
Create Date: 2017-05-24 13:49:31.910594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a80166a46ec'
down_revision = '7f234c96d8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('dataset_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subject', 'dataset', ['dataset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'dataset_id')
    # ### end Alembic commands ###
