"""empty message

Revision ID: 503160b096f3
Revises: c2c9c1a2e869
Create Date: 2017-05-31 12:09:58.993428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503160b096f3'
down_revision = 'c2c9c1a2e869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('mmse', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'mmse')
    # ### end Alembic commands ###
