"""empty message

Revision ID: 594ceb1b2f91
Revises: 4a80166a46ec
Create Date: 2017-05-24 15:44:32.528410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '594ceb1b2f91'
down_revision = '4a80166a46ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('code_temp', sa.String(length=12), nullable=False))
    op.drop_column('dataset', 'code')
    op.drop_column('subject', 'id')
    op.drop_index('code', table_name='tract')
    op.drop_column('tract', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tract', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.create_index('code', 'tract', ['code'], unique=True)
    op.add_column('subject', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.add_column('dataset', sa.Column('code', mysql.VARCHAR(length=12), nullable=False))
    op.drop_column('dataset', 'code_temp')
    # ### end Alembic commands ###
