"""empty message

Revision ID: 6dacf0a3a80d
Revises: 948f9196f741
Create Date: 2018-02-15 16:37:20.358529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dacf0a3a80d'
down_revision = '948f9196f741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesion_upload', sa.Column('RAS', sa.String(length=1), nullable=True))
    op.add_column('lesion_upload', sa.Column('dim_match', sa.String(length=1), nullable=True))
    op.add_column('lesion_upload', sa.Column('pixdim_match', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesion_upload', 'pixdim_match')
    op.drop_column('lesion_upload', 'dim_match')
    op.drop_column('lesion_upload', 'RAS')
    # ### end Alembic commands ###
