"""empty message

Revision ID: 8fd00885914f
Revises: b505073fd5e1
Create Date: 2017-10-05 14:09:02.242095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fd00885914f'
down_revision = 'b505073fd5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_tract_metrics', sa.Column('mean_FA', sa.Float(precision=5), nullable=False))
    op.add_column('subject_tract_metrics', sa.Column('mean_MD', sa.Float(precision=5), nullable=False))
    op.add_column('subject_tract_metrics', sa.Column('std_FA', sa.Float(precision=5), nullable=False))
    op.add_column('subject_tract_metrics', sa.Column('std_MD', sa.Float(precision=5), nullable=False))
    op.drop_column('subject_tract_metrics', 'std')
    op.drop_column('subject_tract_metrics', 'mean')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_tract_metrics', sa.Column('mean', mysql.FLOAT(), nullable=False))
    op.add_column('subject_tract_metrics', sa.Column('std', mysql.FLOAT(), nullable=False))
    op.drop_column('subject_tract_metrics', 'std_MD')
    op.drop_column('subject_tract_metrics', 'std_FA')
    op.drop_column('subject_tract_metrics', 'mean_MD')
    op.drop_column('subject_tract_metrics', 'mean_FA')
    # ### end Alembic commands ###
