"""empty message

Revision ID: 948f9196f741
Revises: c759ff0e68b6
Create Date: 2017-11-23 14:31:54.835249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948f9196f741'
down_revision = 'c759ff0e68b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dataset_tracts', 'dataset', ['dataset_code'], ['code'], onupdate='CASCADE')
    op.create_foreign_key(None, 'dataset_tracts', 'tract', ['tract_code'], ['code'], onupdate='CASCADE')
    op.drop_constraint('subject_tract_metrics_ibfk_2', 'subject_tract_metrics', type_='foreignkey')
    op.drop_constraint('subject_tract_metrics_ibfk_1', 'subject_tract_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'subject_tract_metrics', 'tract', ['tract_code'], ['code'], onupdate='CASCADE')
    op.create_foreign_key(None, 'subject_tract_metrics', 'subject', ['subject_id'], ['subject_id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject_tract_metrics', type_='foreignkey')
    op.drop_constraint(None, 'subject_tract_metrics', type_='foreignkey')
    op.create_foreign_key('subject_tract_metrics_ibfk_1', 'subject_tract_metrics', 'subject', ['subject_id'], ['subject_id'])
    op.create_foreign_key('subject_tract_metrics_ibfk_2', 'subject_tract_metrics', 'tract', ['tract_code'], ['code'])
    op.drop_constraint(None, 'dataset_tracts', type_='foreignkey')
    op.drop_constraint(None, 'dataset_tracts', type_='foreignkey')
    # ### end Alembic commands ###
