"""empty message

Revision ID: b199e8352ef4
Revises: a49314ebae7b
Create Date: 2017-05-24 13:10:40.468918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b199e8352ef4'
down_revision = 'a49314ebae7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tract', 'code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('tract', 'file_path',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tract', 'name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tract', 'name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tract', 'file_path',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tract', 'code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
