"""empty message

Revision ID: b505073fd5e1
Revises: 318c7fd5dff0
Create Date: 2017-08-31 11:27:43.738670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b505073fd5e1'
down_revision = '318c7fd5dff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tract', sa.Column('description', sa.String(length=2000), nullable=True))
    op.create_unique_constraint(None, 'tract', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tract', type_='unique')
    op.drop_column('tract', 'description')
    # ### end Alembic commands ###
