"""empty message

Revision ID: b88cb2598668
Revises: d96b61e742e4
Create Date: 2019-02-06 16:27:13.585971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88cb2598668'
down_revision = 'd96b61e742e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cortical_label',
    sa.Column('atlas_name', sa.String(length=20), nullable=False),
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('label_value', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('atlas_name', 'region_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cortical_label')
    # ### end Alembic commands ###
