"""empty message

Revision ID: b99eabc659d6
Revises: 3a1eaa6435d6
Create Date: 2018-06-28 16:52:05.356328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99eabc659d6'
down_revision = '3a1eaa6435d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dataset_tracts', 'method', ['method_code'], ['code'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dataset_tracts', type_='foreignkey')
    # ### end Alembic commands ###
