"""empty message

Revision ID: c2c9c1a2e869
Revises: 23fe2b14fe74
Create Date: 2017-05-24 15:57:27.860700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c9c1a2e869'
down_revision = '23fe2b14fe74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dataset', ['file_path'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dataset', type_='unique')
    # ### end Alembic commands ###
