"""empty message

Revision ID: d96b61e742e4
Revises: b99eabc659d6
Create Date: 2018-07-06 14:55:37.536549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96b61e742e4'
down_revision = 'b99eabc659d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_tract_metrics', sa.Column('method_code', sa.String(length=12), nullable=False))
    op.create_foreign_key(None, 'subject_tract_metrics', 'method', ['method_code'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject_tract_metrics', type_='foreignkey')
    op.drop_column('subject_tract_metrics', 'method_code')
    # ### end Alembic commands ###
